# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Install curl and bash
RUN apk add --no-cache curl bash \
    && curl -fsSL https://bun.sh/install | bash \
    && mv /root/.bun/bin/bun /usr/local/bin/

WORKDIR /app

# Copy package files and source
COPY package.json package-lock.json* yarn.lock* pnpm-lock.yaml* ./
COPY . .

# Install dependencies and build
RUN bun install
RUN bun build src/index.ts --outdir build --target node
RUN bun build src/server/http-server.ts --outdir build --target node --outfile http-server.js

# Default command
CMD ["node", "build/index.js"]
